from __future__ import annotations

import asyncio

from openai import AsyncOpenAI

import app.db.qdrant_client as qdrant_module
from app.config import get_settings
from app.core.multimodal import MultiModalIngestPipeline
from app.db.qdrant_client import QdrantService

CLINICAL_NOTES = [
    """Follow-up visit for a 68-year-old man with established Type 2 Diabetes Mellitus and longstanding hypertension. He reports reasonable medication adherence, but diet quality has fluctuated over the last two months due to travel and reduced exercise. Current medications include metformin 1000 mg twice daily and lisinopril 10 mg daily. Home blood pressure averages in the low 140s systolic, and today in clinic blood pressure is 142/88 mmHg. He denies chest pain, dyspnea, orthopnea, lower extremity edema, focal neurologic symptoms, and episodes of hypoglycemia. Laboratory review shows HbA1c 7.8%, creatinine stable, and eGFR 62 mL/min/1.73m2. Urine albumin is mildly elevated compared with prior baseline. Given persistent hyperglycemia despite maximized metformin and preserved renal function, plan is to initiate empagliflozin for additional glycemic control and cardiorenal protection. Counseling was provided regarding genital mycotic infection risk, sick-day rules, hydration status, and temporary medication hold if acutely ill. Continue lisinopril and reinforce sodium restriction and daily walking. Repeat HbA1c, BMP, and urine albumin-to-creatinine ratio in approximately 12 weeks to assess response and renal trajectory.""",
    """74-year-old woman with chronic HFrEF (most recent LVEF 35%) and atrial fibrillation presents with progressive exertional dyspnea and mild weight gain over one week. Current medications include warfarin 5 mg nightly, metoprolol tartrate 50 mg twice daily, and furosemide 40 mg daily. She notes increasing ankle swelling and sleeping with two pillows but denies chest pain, syncope, and fever. Vital signs are stable, heart rhythm irregularly irregular, and bibasilar crackles are present without acute respiratory distress. Laboratory data: BNP 820 pg/mL, INR 2.6 in therapeutic range, creatinine slightly above baseline but acceptable for diuresis escalation. Clinical picture is consistent with volume overload in chronic systolic heart failure without evidence of cardiogenic shock. Plan is to increase furosemide dose with close outpatient monitoring of renal function, sodium, potassium, and daily weight trend. Anticoagulation with warfarin remains indicated for stroke prevention in AF and is continued at current dose pending repeat INR next week. She was instructed on low-sodium diet, fluid moderation, and urgent return precautions for worsening orthopnea, severe dyspnea, or rapid weight gain. Follow-up arranged in heart failure clinic within 5 to 7 days.""",
    """55-year-old man with severe COPD, GOLD stage III, evaluated after recent exacerbation characterized by increased cough, sputum production, and breathlessness above baseline. He currently uses albuterol inhaler as needed and tiotropium daily maintenance. Pulmonary function testing confirms obstructive physiology with FEV1/FVC ratio 0.58 and reduced FEV1 consistent with advanced airflow limitation. He completed short-acting bronchodilator intensification at home but had persistent wheeze and chest tightness, prompting clinic reassessment. No fever or focal consolidation signs today, and oxygen saturation is acceptable at rest. Management plan includes prednisone 40 mg daily for 5 days for acute inflammatory control, continuation of long-acting antimuscarinic therapy, and reinforced inhaler technique. He was counseled to monitor rescue inhaler frequency and seek urgent care for increased work of breathing, inability to speak full sentences, or oxygen desaturation. Smoking abstinence remains critical and was revisited in detail, including relapse prevention strategies. Vaccination status was reviewed with recommendation for seasonal influenza and pneumococcal updates. Follow-up in 2 weeks to assess symptom recovery and determine whether escalation to dual long-acting bronchodilator regimen is warranted.""",
    """Initial endocrine visit for a 45-year-old woman with new biochemical hypothyroidism and six months of progressive fatigue, cold intolerance, and unintentional weight gain. She reports dry skin, reduced exercise tolerance, and mild constipation, but no chest pain, palpitations, or tremor. Recent labs show TSH 8.2 mIU/L with free T4 0.6 ng/dL, supporting overt primary hypothyroidism. Family history is notable for autoimmune thyroid disease in a first-degree relative. Physical exam reveals mild delayed relaxation of deep tendon reflexes without goiter-related compressive symptoms. She is started on levothyroxine 50 mcg every morning on an empty stomach, with counseling to separate administration from calcium, iron, and multivitamins by at least four hours to avoid absorption variability. Discussed expected timeline for symptomatic improvement, emphasizing that full response may take several weeks. Plan includes repeat TSH and free T4 in 6 to 8 weeks for dose adjustment and long-term titration toward euthyroid range. She was advised to report symptoms of overtreatment such as palpitations, insomnia, or heat intolerance. Follow-up scheduled to review laboratory trend, symptom burden, and adherence.""",
    """Psychiatry intake for a 32-year-old man with major depressive disorder presenting with depressed mood, anhedonia, low motivation, poor concentration, and early morning awakening over the past two months. PHQ-9 score today is 18, indicating moderately severe depression. He denies current substance misuse, manic symptoms, or psychotic features. Appetite has decreased and occupational functioning is impaired, with frequent missed deadlines. No current suicidal plan or intent, but passive hopelessness thoughts are present and were explored in detail with a documented safety plan. After discussion of treatment options, sertraline 50 mg daily is initiated with plan to increase to 100 mg at week 4 if tolerated and if partial response persists. Counseling included expected latency to antidepressant effect, common transient adverse effects such as nausea and sleep disturbance, and sexual side effect risk. Patient was informed about monitoring for activation and suicidality, particularly early in therapy. Referral for structured psychotherapy was placed, and behavioral activation goals were set. Follow-up is arranged in 4 weeks with interim crisis instructions and emergency contact resources reviewed.""",
    """Anticoagulation management visit for an 80-year-old woman on chronic warfarin 4 mg daily for atrial fibrillation stroke prophylaxis. She has no overt bleeding symptoms today, denies melena, hematuria, epistaxis, or neurologic deficit, and remains hemodynamically stable. Point-of-care INR is supratherapeutic at 3.8, above individualized target range. Medication reconciliation identifies a recent amoxicillin course for urinary tract infection completed earlier this week, likely contributing through reduced gut flora vitamin K production and potentiation of warfarin effect. Diet has otherwise been stable. Plan is to hold one warfarin dose and resume adjusted regimen with repeat INR in 3 days for close reassessment. Patient was counseled extensively on warning signs of hemorrhage, avoidance of new over-the-counter NSAID exposure, and need to communicate all antibiotic starts to anticoagulation clinic. No current indication for reversal agent given absence of active bleeding and modest INR elevation. AF rate control remains stable on baseline regimen. Follow-up contact scheduled with nurse anticoagulation service to confirm repeat testing and dose titration based on trend.""",
    """Diabetes follow-up for a 52-year-old man with poor glycemic control and early chronic kidney disease. Current HbA1c is 9.2%, fasting glucose readings frequently above 180 mg/dL, and eGFR has declined to 45 mL/min/1.73m2. He has been taking metformin 1000 mg twice daily but reports occasional missed evening doses. Given renal trajectory and elevated risk of adverse effects with higher metformin exposure, metformin is reduced to 500 mg twice daily. Due to persistent hyperglycemia despite oral therapy, basal insulin initiation is recommended and accepted. Insulin glargine is started at 10 units nightly with a clear titration plan based on fasting glucose targets. Education covered injection technique, site rotation, hypoglycemia recognition, and corrective actions including rapid carbohydrate intake and recheck protocol. He denies severe hypoglycemia history. Lifestyle counseling focused on carbohydrate distribution, evening snacking reduction, and walking after meals. Plan includes close follow-up in 2 to 3 weeks for insulin titration, and repeat BMP with renal function and potassium monitoring. If control remains suboptimal, future addition of cardiorenal protective therapy will be revisited.""",
    """Cardiovascular risk management follow-up for a 61-year-old woman with dyslipidemia on atorvastatin 20 mg daily. Despite adherence, LDL remains elevated at 168 mg/dL. She reports no myalgias, weakness, or dark urine, and liver profile including ALT is within normal range. Ten-year ASCVD risk is calculated at 18%, placing her in a high-risk primary prevention category where more intensive LDL lowering is indicated. Decision made to increase atorvastatin dose to 40 mg nightly as high-intensity strategy. Counseling addressed potential adverse effects, particularly muscle symptoms and rare hepatic enzyme elevation, and the need to notify clinic promptly if concerning symptoms arise. Reinforced Mediterranean-style dietary pattern, soluble fiber intake, and regular aerobic exercise as adjuncts to pharmacotherapy. Blood pressure and glycemic parameters are currently acceptable. Plan is to repeat lipid panel and hepatic enzymes in approximately 8 weeks to assess therapeutic response and tolerability. If LDL remains above target despite adherence, consideration will be given to further intensification with combination lipid-lowering therapy based on shared decision-making.""",
    """Primary care new diagnosis encounter for a 48-year-old man with repeated elevated blood pressure readings and no prior antihypertensive therapy. Office blood pressure today is 156/94 mmHg, consistent with stage 2 hypertension after confirmation across prior visits. He denies headache, visual changes, focal neurologic deficits, chest pain, dyspnea, and edema. Baseline renal function and electrolytes are currently within acceptable limits. Given sustained elevation and overall cardiovascular risk profile, amlodipine 5 mg daily is initiated. Discussed expected blood pressure response timeline, common dose-related peripheral edema, and when to contact clinic for side effects. Intensive lifestyle counseling provided, including DASH dietary approach, sodium reduction, moderation of alcohol intake, and goal of at least 150 minutes per week of moderate aerobic activity. Home blood pressure monitoring technique was reviewed and patient instructed to keep a daily log. No immediate evidence of hypertensive emergency or end-organ injury on current evaluation. Follow-up scheduled in 4 weeks for blood pressure reassessment and dose titration if needed, with earlier review for adverse effects or persistently severe home readings.""",
    """Gastroenterology follow-up for a 70-year-old woman with confirmed peptic ulcer disease and positive Helicobacter pylori testing. She reports epigastric pain and postprandial burning over several weeks without hematemesis or hemodynamic instability. Stool color has been normal and no recent NSAID overuse is reported. Management plan is standard triple therapy: amoxicillin 1 g twice daily, clarithromycin 500 mg twice daily, and omeprazole 20 mg twice daily for 14 days. Medication instructions emphasized strict adherence to full regimen duration to maximize eradication probability and reduce resistance risk. She was counseled on expected GI adverse effects, potential taste disturbance with clarithromycin, and red-flag symptoms such as melena, persistent vomiting, or severe abdominal pain requiring urgent reassessment. Acid suppression continuation strategy after eradication course was discussed based on symptom response and risk profile. We reviewed avoidance of smoking and alcohol excess to support mucosal healing. Follow-up testing for eradication is planned after appropriate post-treatment interval using noninvasive confirmation protocol. Return visit arranged to assess symptom resolution and finalize long-term prevention counseling.""",
]


LAB_SETS = [
    {"HbA1c": 8.2, "fasting_glucose": 187, "eGFR": 52, "potassium": 4.1, "creatinine": 1.4},
    {"BNP": 820, "sodium": 134, "potassium": 3.2, "creatinine": 1.8, "eGFR": 38},
    {"TSH": 8.2, "free_t4": 0.6, "ldl": 145, "fasting_glucose": 95},
    {"INR": 3.8, "potassium": 4.0, "creatinine": 1.1, "eGFR": 68},
    {"HbA1c": 9.2, "fasting_glucose": 218, "eGFR": 45, "potassium": 4.8, "ldl": 132},
]


async def main() -> None:
    settings = get_settings()

    service = QdrantService(host=settings.QDRANT_HOST, port=settings.QDRANT_PORT)
    qdrant_module.qdrant_service = service

    print("Initializing Qdrant collections...")
    await service.initialize()

    openai_client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
    pipeline = MultiModalIngestPipeline(openai_client)

    print("Seeding clinical note vectors...")
    for idx, note in enumerate(CLINICAL_NOTES, start=1):
        doc_id, entities = await pipeline.ingest_text(
            note,
            source=f"seed://clinical_note/{idx}",
            metadata={"seeded": True, "note_index": idx, "domain": "synthetic_clinical_note"},
        )
        print(f"  note {idx:02d}: doc_id={doc_id}, entities={len(entities)}")

    print("Seeding lab table vectors...")
    for idx, labs in enumerate(LAB_SETS, start=1):
        doc_id, abnormal = await pipeline.ingest_lab_table(
            labs,
            metadata={"seeded": True, "lab_set_index": idx, "domain": "synthetic_labs"},
        )
        print(f"  labs {idx:02d}: doc_id={doc_id}, abnormal_values={len(abnormal)}")

    print("Vector seed complete.")


if __name__ == "__main__":
    asyncio.run(main())
